# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "Lruihao"
email = "1024@lruihao.cn"
link = "https://github.com/Lruihao"
