# -------------------------------------------------------------------------------------
# Multilingual mode
# See: https://gohugo.io/content-management/multilingual/#configure-languages
# -------------------------------------------------------------------------------------

weight = 2
languageCode = "zh-TW"
languageName = "繁體中文"
hasCJKLanguage = true
copyright = "本站內容採用 CC BY-NC-SA 4.0 國際授權條款。"
