# -------------------------------------------------------------------------------------
# Multilingual mode
# See: https://gohugo.io/content-management/multilingual/#configure-languages
# -------------------------------------------------------------------------------------

weight = 1
languageCode = "zh-CN"
languageName = "简体中文"
hasCJKLanguage = true
copyright = "本站内容采用 CC BY-NC-SA 4.0 国际许可协议。"
