# -------------------------------------------------------------------------------------
# Permalinks Configuration
# See: https://gohugo.io/content-management/urls/#permalinks
# -------------------------------------------------------------------------------------

# posts = ":year/:month/:filename"
posts = "posts/:slugorcontentbasename"
private = ":sections[1:]/:slugorcontentbasename"

# [page]
# [section]
# [taxonomy]
# [term]
