# -------------------------------------------------------------------------------------
# Privacy Configuration
# See: https://gohugo.io/configuration/privacy/
# -------------------------------------------------------------------------------------

[x]
enableDNT = true

[youtube]
privacyEnhanced = true
