# -------------------------------------------------------------------------------------
# Sitemap Configuration
# See: https://gohugo.io/templates/sitemap/#configuration
# -------------------------------------------------------------------------------------

changefreq = "weekly"
disable = false
filename = "sitemap.xml"
priority = 0.5
