# -------------------------------------------------------------------------------------
# Taxonomies Configuration
# See: https://gohugo.io/configuration/taxonomies/
# -------------------------------------------------------------------------------------

_merge = "shallow"
category = "categories"
tag = "tags"
collection = "collections"
